### ISSUE TITLE
3D Tiles Anwendertreffen, 3DCitydb workflow

### ISSUE THREAD

**Issue by stefan-overkamp** [pka/awesome-3d-tiles#2]
In the Anwendertreffen it was said, that 3DCityDB-Exporter could export 3D-Tiles-Format.
I don't think this is correct. Have not found any configuration that could do that.

In an older issue (https://github.com/3dcitydb/importer-exporter/issues/13) one can read
"The 3DCityDB cannot export b3dm files.  ... We have however a converter which creates b3dm files 
from a 3DCityDB.. but its not open-source unfortunately.."

My way to try 3D-Tiles in MapStore2 was to 
- Import citygml into 3DCityDB (https://www.opengeodata.nrw.de/produkte/geobasis/3dg/lod2_gml/lod2_gml/)
- Export as Collada/glTF
- Convert to 3dtiles with Cesium Ion 

I am interested in other possible workflows to handle 3D building models and produce 3D-Tiles-Format.

**Comment by pka** [comment]
Thanks for this feedback. I can't remember where I had the this information from. Maybe I mixed it up with the x3dm converter from Virtual City Systems?

Anyway, your workflow description is exactly what we want to collect here. I've activated the discussion forum, which is probably a better place to collect information like this.
